spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySql Driver
    url: jdbc:mysql://localhost:3306/UnivPortalSystem?serverTimezone=UTC&characterEncoding=UTF-8 # DB Source URL
    username: root # DB username
    password: 1234 # DB password
  jpa:
    show-sql: true     # ??? ???? SQL? ??? ??? ??
    hibernate:
      ddl-auto: update # ???? ??? ???? DDL(create, alter, drop) ? ??? ? ?? ???? ??
                       # create : ?? ??? ??? ?? ????
                       # update : ??? ??? ?? alter? ???? ???? ???? create? ??
  properties:
    hibernate:
      format_sql: true # ?? JPA ???? Hibernate? ????? ???? SQL? ????? ???? -> ???? SQL? ???? ????