spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySql Driver
    url: jdbc:mysql://localhost:3306/UnivPortalSystem?serverTimezone=UTC&characterEncoding=UTF-8 # DB Source URL
    username: root # DB username
    password: 1234 # DB password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      format_sql: true
  devtools:
    livereload:
      enabled: true # template, static resource 실시간 반영 설정
    freemarker:
      cache: false # template, static resource 실시간 반영 설정